name: update sanity display in development mode

on:
  repository_dispatch:
    types: [sanity-webhook]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print workspace directory
        run: echo ${{ github.workspace }}

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: npm install

#      - name: Install Gatsby
#        run: npm install -g gatsby-cli

      - name: Clean Gatsby cache
        run: npx gatsby clean

      - name: Start Gatsby development server
        run: npx gatsby develop