name: Trigger update sanity display in development mode

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the workflow to trigger'
        required: true
        default: 'update sanity display in development mode'

jobs:
  trigger:
    runs-on: macos-latest
    steps:
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'
      - name: Print webhook token
        run: echo ${{ secrets.PAT_TOKEN }}
      - name: Trigger workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          event-type: sanity-webhook
          client-payload: '{"name": "${{ github.event.inputs.name }}"}'